DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;

CREATE TABLE AUTHORS(ID BIGINT auto_increment PRIMARY KEY,
                SHORTNAME VARCHAR(255),
                FULLNAME VARCHAR(255),
                BIRTHDATE DATE);

CREATE TABLE GENRES(ID BIGINT auto_increment PRIMARY KEY,
                NAME VARCHAR(255));

CREATE TABLE BOOKS(ID BIGINT auto_increment PRIMARY KEY,
                TITLE VARCHAR(255),
                AUTHORID BIGINT,
                FOREIGN KEY (AUTHORID) REFERENCES AUTHORS(ID),
                GENREID BIGINT,
                FOREIGN KEY (GENREID) REFERENCES GENRES(ID));

CREATE TABLE COMMENTS(ID BIGINT auto_increment PRIMARY KEY,
                MESSAGE VARCHAR,
                BOOKID BIGINT,
                FOREIGN KEY(BOOKID) REFERENCES BOOKS(ID) on delete cascade);